ghc: 7.6

sudo: required

before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -qq build-essential libghc-ncurses-dev ncurses-dev

script:
  - cabal install bimap bitset parse-dimacs hxt-relaxng
  - cabal install hatt fgl graphviz
  - cabal install syb MissingH
  - make test-products
