

module HplAssets.ComponentModel.Parsers.AbsComponentModel where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq,Ord,Show,Read)
data ComponentModel =
   TComponentModel SrcDir [ComponentMapping]
  deriving (Eq,Ord,Show,Read)

data SrcDir =
   TSrcDir FPath
  deriving (Eq,Ord,Show,Read)

data ComponentMapping =
   TComponentMapping Ident FPath
  deriving (Eq,Ord,Show,Read)

data FPath =
   BasicFPath Ident
 | BasicFPathExt Ident Ident
 | BasicFPathExt2 Ident FPath
 | BasicFileExt Ident
 | ComposedFPath Ident FPath
 | AbsoluteFPath FPath
  deriving (Eq,Ord,Show,Read)

