{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module HplAssets.ComponentModel.Parsers.PrintComponentModel where

-- pretty-printer generated by the BNF converter

import HplAssets.ComponentModel.Parsers.AbsComponentModel
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print ComponentModel where
  prt i e = case e of
   TComponentModel srcdir componentmappings -> prPrec i 0 (concatD [prt 0 srcdir , prt 0 componentmappings])


instance Print SrcDir where
  prt i e = case e of
   TSrcDir fpath -> prPrec i 0 (concatD [doc (showString "src-dir") , doc (showString "=") , prt 0 fpath , doc (showString ";")])


instance Print ComponentMapping where
  prt i e = case e of
   TComponentMapping id fpaths -> prPrec i 0 (concatD [prt 0 id , doc (showString "=>") , doc (showString "[") , prt 0 fpaths , doc (showString "]")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print FPath where
  prt i e = case e of
   BasicFPath id -> prPrec i 0 (concatD [prt 0 id])
   BasicFPathExt id0 id -> prPrec i 0 (concatD [prt 0 id0 , doc (showString ".") , prt 0 id])
   BasicFPathExt2 id fpath -> prPrec i 0 (concatD [prt 0 id , doc (showString "-") , prt 0 fpath])
   BasicFileExt id -> prPrec i 0 (concatD [doc (showString ".") , prt 0 id])
   ComposedFPath id fpath -> prPrec i 0 (concatD [prt 0 id , doc (showString "/") , prt 0 fpath])
   AbsoluteFPath fpath -> prPrec i 0 (concatD [doc (showString "/") , prt 0 fpath])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])


