{-# OPTIONS -fno-warn-incomplete-patterns #-}
module UseCaseModel.Parsers.BNFC.PrintUCM where

-- pretty-printer generated by the BNF converter

import UseCaseModel.Parsers.BNFC.AbsUCM
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)



instance Print Advice where
  prt i e = case e of
   TBeforeAdvice advicedec -> prPrec i 0 (concatD [doc (showString "before") , prt 0 advicedec])
   TAfterAdvice advicedec -> prPrec i 0 (concatD [doc (showString "after") , prt 0 advicedec])
   TAroundAdvice advicedec -> prPrec i 0 (concatD [doc (showString "around") , prt 0 advicedec])


instance Print AdviceDec where
  prt i e = case e of
   TAdviceDec advid advdesc flow -> prPrec i 0 (concatD [doc (showString "advice") , doc (showString "{") , prt 0 advid , doc (showString ";") , prt 0 advdesc , doc (showString ";") , prt 0 flow , doc (showString "}")])


instance Print AdvId where
  prt i e = case e of
   TAdvId id -> prPrec i 0 (concatD [doc (showString "id") , doc (showString ":") , prt 0 id])


instance Print AdvDesc where
  prt i e = case e of
   TAdvDesc str -> prPrec i 0 (concatD [doc (showString "description") , doc (showString ":") , prt 0 str])


instance Print Flow where
  prt i e = case e of
   TFlow steps -> prPrec i 0 (concatD [prt 0 steps])


instance Print Step where
  prt i e = case e of
   TBasicStep stepid action system response -> prPrec i 0 (concatD [doc (showString "Step") , doc (showString "(") , prt 0 stepid , doc (showString ",") , prt 0 action , doc (showString ",") , prt 0 system , doc (showString ",") , prt 0 response , doc (showString ")")])
   TProceed  -> prPrec i 0 (concatD [doc (showString "Proceed")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Action where
  prt i e = case e of
   TAction str -> prPrec i 0 (concatD [prt 0 str])


instance Print System where
  prt i e = case e of
   TSystem str -> prPrec i 0 (concatD [prt 0 str])


instance Print Response where
  prt i e = case e of
   TResponse str -> prPrec i 0 (concatD [prt 0 str])


instance Print StepId where
  prt i e = case e of
   TStepId id -> prPrec i 0 (concatD [prt 0 id])



