{-# OPTIONS -fno-warn-incomplete-patterns #-}
module FeatureModel.Parsers.FMGrammar.PrintFMGrammar where

-- pretty-printer generated by the BNF converter

import FeatureModel.Parsers.FMGrammar.AbsFMGrammar
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)



instance Print FMGrammar where
  prt i e = case e of
   FMGrammar productions expressions -> prPrec i 0 (concatD [prt 0 productions , prt 0 expressions])


instance Print Production where
  prt i e = case e of
   BaseProduction id childs -> prPrec i 0 (concatD [prt 0 id , doc (showString ":") , prt 0 childs , doc (showString ";/")])
   XorProduction id options -> prPrec i 0 (concatD [prt 0 id , doc (showString ":") , doc (showString "(") , prt 0 options , doc (showString ")") , doc (showString ";/")])
   OrProduction id options -> prPrec i 0 (concatD [prt 0 id , doc (showString ":") , doc (showString "(") , prt 0 options , doc (showString ")+") , doc (showString ";/")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Child where
  prt i e = case e of
   MandatoryChild id -> prPrec i 0 (concatD [prt 0 id])
   OptionalChild id -> prPrec i 0 (concatD [prt 0 id , doc (showString "?")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Option where
  prt i e = case e of
   Option id -> prPrec i 0 (concatD [prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "|") , prt 0 xs])

instance Print Expression where
  prt i e = case e of
   BasicExp id -> prPrec i 0 (concatD [prt 0 id])
   ImpliesExp expression0 expression -> prPrec i 0 (concatD [doc (showString "(") , prt 0 expression0 , doc (showString "->") , prt 0 expression , doc (showString ")")])
   IffExp expression0 expression -> prPrec i 0 (concatD [doc (showString "(") , prt 0 expression0 , doc (showString "<->") , prt 0 expression , doc (showString ")")])
   AndExp expression0 expression -> prPrec i 0 (concatD [doc (showString "(") , prt 0 expression0 , doc (showString "&") , prt 0 expression , doc (showString ")")])
   OrExp expression0 expression -> prPrec i 0 (concatD [doc (showString "(") , prt 0 expression0 , doc (showString "|") , prt 0 expression , doc (showString ")")])
   NotExp expression -> prPrec i 0 (concatD [doc (showString "!") , prt 0 expression])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";/") , prt 0 xs])


