{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module FeatureModel.Parsers.SXFM.PrintSXFM where

-- pretty-printer generated by the BNF converter

import FeatureModel.Parsers.SXFM.AbsSXFM
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print SxFM where
  prt i e = case e of
   TSxFM sxfeatureroot -> prPrec i 0 (concatD [prt 0 sxfeatureroot])


instance Print SxFeatureRoot where
  prt i e = case e of
   TSxFeatureRoot sxfeaturename sxfeatureid sxfeatures -> prPrec i 0 (concatD [doc (showString ":r") , prt 0 sxfeaturename , prt 0 sxfeatureid , doc (showString "(") , prt 0 sxfeatures , doc (showString ")")])


instance Print SxFeatureName where
  prt i e = case e of
   TSxFeatureName id -> prPrec i 0 (concatD [prt 0 id])


instance Print SxFeatureId where
  prt i e = case e of
   TSxFeatureId id -> prPrec i 0 (concatD [doc (showString "(") , prt 0 id , doc (showString ")")])


instance Print SxFeature where
  prt i e = case e of
   TSxMandatoryFeature sxfeaturename sxfeatures -> prPrec i 0 (concatD [doc (showString ":m") , prt 0 sxfeaturename , doc (showString "(") , prt 0 sxfeatures , doc (showString ")")])
   TSxOptionalFeature sxfeaturename sxfeatures -> prPrec i 0 (concatD [doc (showString ":o") , prt 0 sxfeaturename , doc (showString "(") , prt 0 sxfeatures , doc (showString ")")])
   TSxAlternativeFeature sxoptions -> prPrec i 0 (concatD [doc (showString ":g [1,1]") , doc (showString "(") , prt 0 sxoptions , doc (showString ")")])
   TSxOrFeature sxoptions -> prPrec i 0 (concatD [doc (showString ":g [1,*]") , doc (showString "(") , prt 0 sxoptions , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print SxOption where
  prt i e = case e of
   TSxOption id0 id sxfeatures -> prPrec i 0 (concatD [doc (showString ":option") , prt 0 id0 , doc (showString "(") , prt 0 id , doc (showString ")") , doc (showString "(") , prt 0 sxfeatures , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])


