-----------------------------------------------------------------------------
-- |
-- Module      :  ReqModel.PrettyPrinter.Latex
-- Copyright   :  (c) Rodrigo Bonifacio 2008, 2009
-- License     :  LGPL
--
-- Maintainer  :  rba2@cin.ufpe.br
-- Stability   :  provisional
-- Portability :  portable
--
-- A Latex pretty printer for the Requirements Model data type. Useful for 
-- generating ps or pdf files from a requirements model.
--
--
-----------------------------------------------------------------------------

module HplAssets.ReqModel.PrettyPrinter.Latex (exportReqToLatex) where 

import Text.PrettyPrint.HughesPJ
import System.IO
import Control.Exception

import HplAssets.ReqModel.Types

title1 :: String
title1 = "\\title{Requirement Model Generated from "

exportReqToLatex:: FilePath -> RequirementModel -> IO()
exportReqToLatex f req = 
 bracket (openFile f WriteMode)
         hClose
         (\h -> hPutStr h (show (reqModelToLatex req)))


reqModelToLatex :: RequirementModel -> Doc
reqModelToLatex (RM rqs) = vcat [ beginDocument title1 
                                , endDocument
                                ]


beginDocument :: String -> Doc
beginDocument title  =
 vcat [ text "%This Latex file is machine-generated by the Hephaestus\n"
      , text "\\documentclass[a4paper,11pt]{article}" 
      , text "\\newcommand{\\bl}{\\\\ \\hline}"
      , text (title1 ++ "}")
      , text "\\begin{document}" 
      , text "\\maketitle"
      ]

endDocument :: Doc
endDocument =  text "\\end{document}"